baseURL = ''
languageCode = 'en-us'
title = "wh"
theme = 'blog-theme'
googleAnalytics = "G-PCNGEYW1TG"

[params]
  defaultTheme='light'
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    ordered = true
    endLevel = 4

[markup.goldmark.renderer] 
unsafe = true

